Implemented HashTable
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-dmkulazhenko pull request #1
Opened 2020-03-14 17:59 UTC by dmkulazhenko

2020-03-18 16:44 UTC, andrsuh requested changes

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static class Entry {
внутренние классы объявляются после всех методов

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        private Object key, value;
не надо в одну строчку

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +    private final int MAX_INIT_SIZE = 1_000_007;
не до конца верное объявление констант

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        this.loadFactor = this.INIT_LOAD_FACTOR;
конструктор может вызвать другой конструктор

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        if (initSize != null && (initSize <= 0 || initSize > this.MAX_INIT_SIZE)) {
перебор, не было требования по максимальной начальной вместимости

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int getHash(Object key) {
приватный методы объявляются после публичных

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +            hash += this.table.length;
не очень понимаю зачем это условие и что оно гарантирует. объяснить

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        return (hash + this.HASH_STEP) % this.table.length;
this.HASH_STEP так к константам не обращаются, потому что как правило они не требуют обращения по ссылке

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        int hash = this.getHash(key);
это уже индекс, а не хеш

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +            if (key.equals(this.table[hash].key)) {
возможен вечный цикл?

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        if (this.THRESHOLD > this.loadFactor && this.table.length * this.THRESHOLD < this.realSize) {
проверка должны быть не здесь

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
>      Object get(Object key) {
модификатор

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +        while (this.table[hash] != null) {
а если все заняты ячейки?

2020-03-18 16:44 UTC, andrsuh commented on src/main/java/ru/itmo/java/HashTable.java
> +                Object value = this.table[hash].value;
почему бы не сделать предопределенное статическое значение-синглтон как удаленное? и всем его присваивать? `privatr static final Entry DELETED = new Entry(null, null); table[index] = Entry.DELETED`

2020-03-18 16:49 UTC, andrsuh commented
Части кода идентичны работе Романа Михнюка

2020-03-18 16:57 UTC, andrsuh commented
Работа аналогичная одногруппнику. Для обоих за работу нельзя будет получить БОЛЕЕ 30% баллов (6 из 20) после защиты. Если тот, кто списал раскроется, то второму человеку разрешу защищаться на полный балл.

2020-03-20 13:59 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +            if (key.equals(this.table[hash].key)) {
нет, не возможен. она бы ресайзнулась в предыдущих put.

2020-03-20 14:01 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        int hash = this.getHash(key);
он является как и индексом, так и хешом. плюс использование метода nextHash от индекса -- выглядит хуже.

2020-03-20 14:02 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static class Entry {
done

2020-03-20 14:02 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        private Object key, value;
done

2020-03-20 14:05 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +    private final int MAX_INIT_SIZE = 1_000_007;
done

2020-03-20 14:06 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        this.loadFactor = this.INIT_LOAD_FACTOR;
done

2020-03-20 14:07 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        if (initSize != null && (initSize <= 0 || initSize > this.MAX_INIT_SIZE)) {
done

2020-03-20 14:08 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int getHash(Object key) {
done

2020-03-20 14:09 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +            hash += this.table.length;
hash code can be negative

2020-03-20 14:09 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        return (hash + this.HASH_STEP) % this.table.length;
done

2020-03-20 14:10 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        if (this.THRESHOLD > this.loadFactor && this.table.length * this.THRESHOLD < this.realSize) {
done

2020-03-20 14:12 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +        while (this.table[hash] != null) {
такое невозможно из-за того, что мы выделяем память при ее отсутствии.

2020-03-20 14:16 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
> +                Object value = this.table[hash].value;
done

2020-03-20 14:24 UTC, dmkulazhenko commented on src/main/java/ru/itmo/java/HashTable.java
>      Object get(Object key) {
package private вполне достаточно в текущей задаче, но раз с public будет спокойнее, то сделаю

2023-03-17 11:14 UTC, closed without merging